// GpsTrackerProtocolOptions.cs
using Microsoft.Extensions.Options;
using System.ComponentModel.DataAnnotations;

namespace GpsTrackerProtocol.Configuration;

/// <summary>
/// Configuration options for the GPS tracker protocol service.
/// Defines settings for protocol selection, device limits, caching, rate limiting,
/// and protocol-specific configurations for supported tracker protocols.
/// </summary>
public class GpsTrackerProtocolOptions
{
    /// <summary>
    /// Gets or sets the default protocol to use when processing GPS tracker data.
    /// This value determines which protocol implementation will be used as the primary protocol.
    /// Supported values: "GT06", "H02", "TK103".
    /// </summary>
    [Required]
    public string DefaultProtocol { get; set; } = "GT06";

    /// <summary>
    /// Gets or sets the maximum number of devices that can be tracked simultaneously.
    /// This limit prevents resource exhaustion by restricting the number of concurrent connections.
    /// Range: 1 to 10000 devices.
    /// </summary>
    [Range(1, 10000)]
    public int MaxDevices { get; set; } = 10000;

    /// <summary>
    /// Gets or sets the maximum number of location records to retain in history per device.
    /// Older records beyond this limit will be automatically pruned to prevent unbounded memory growth.
    /// Range: 1 to 1000 location records.
    /// </summary>
    [Range(1, 1000)]
    public int LocationHistoryLimit { get; set; } = 1000;

    /// <summary>
    /// Gets or sets the duration in minutes that cached data should remain valid before expiration.
    /// This controls how frequently protocol-specific data needs to be refreshed from configuration sources.
    /// Range: 1 to 60 minutes.
    /// </summary>
    [Range(1, 60)]
    public int CacheExpirationMinutes { get; set; } = 60;

    /// <summary>
    /// Gets or sets the maximum number of requests allowed per minute from a single client.
    /// This rate limit helps prevent abuse and ensures fair resource allocation across all connected devices.
    /// Range: 1 to 1000 requests per minute.
    /// </summary>
    [Range(1, 1000)]
    public int RateLimitPerMinute { get; set; } = 1000;

    /// <summary>
    /// Gets or sets the logging level for the GPS tracker protocol service.
    /// Controls the verbosity of diagnostic and operational logs generated by the protocol handlers.
    /// Common values: "Debug", "Information", "Warning", "Error", "Critical".
    /// </summary>
    [Required]
    public string LoggingLevel { get; set; } = "Information";

    public ProtocolSettings Protocol { get; set; } = new ProtocolSettings();

    /// <summary>
    /// Contains protocol-specific configuration settings for each supported GPS tracker protocol.
    /// Each protocol has its own timeout, maximum frame size, and enable/disable flag.
    /// </summary>
    public class ProtocolSettings
    {
        /// <summary>
    /// Gets or sets a value indicating whether the GT06 protocol is enabled.
    /// When true, the service will process GT06 protocol messages from connected devices.
    /// </summary>
    public bool GT06Enabled { get; set; } = true;
        /// <summary>
    /// Gets or sets the timeout in seconds for GT06 protocol connections.
    /// This value determines how long the service will wait for a complete message from a GT06 device
    /// before considering the connection inactive and closing it.
    /// </summary>
    public int GT06Timeout { get; set; } = 30;
        /// <summary>
    /// Gets or sets the maximum frame size in bytes for GT06 protocol messages.
    /// This limit prevents memory exhaustion by restricting the size of individual protocol messages
    /// that can be received from GT06 devices.
    /// </summary>
    public int GT06MaxFrameSize { get; set; } = 200;

        /// <summary>
    /// Gets or sets a value indicating whether the H02 protocol is enabled.
    /// When true, the service will process H02 protocol messages from connected devices.
    /// </summary>
    public bool H02Enabled { get; set; } = true;
        /// <summary>
    /// Gets or sets the timeout in seconds for H02 protocol connections.
    /// This value determines how long the service will wait for a complete message from an H02 device
    /// before considering the connection inactive and closing it.
    /// </summary>
    public int H02Timeout { get; set; } = 30;
        /// <summary>
    /// Gets or sets the maximum frame size in bytes for H02 protocol messages.
    /// This limit prevents memory exhaustion by restricting the size of individual protocol messages
    /// that can be received from H02 devices.
    /// </summary>
    public int H02MaxFrameSize { get; set; } = 300;

        /// <summary>
    /// Gets or sets a value indicating whether the TK103 protocol is enabled.
    /// When true, the service will process TK103 protocol messages from connected devices.
    /// </summary>
    public bool TK103Enabled { get; set; } = true;
        /// <summary>
    /// Gets or sets the timeout in seconds for TK103 protocol connections.
    /// This value determines how long the service will wait for a complete message from a TK103 device
    /// before considering the connection inactive and closing it.
    /// </summary>
    public int TK103Timeout { get; set; } = 30;
        /// <summary>
    /// Gets or sets the maximum frame size in bytes for TK103 protocol messages.
    /// This limit prevents memory exhaustion by restricting the size of individual protocol messages
    /// that can be received from TK103 devices.
    /// </summary>
    public int TK103MaxFrameSize { get; set; } = 100;
    }
}
